### ISSUE TITLE
removeReadData should be a constructor parameter.

### ISSUE THREAD

**Issue by Orace** [MarcusChr/BlockBasedMemoryStream#5]
To have a `SlidingStream` or `QueueStream` like [discussed here](https://stackoverflow.com/questions/8221136), there should be a `removeReadData` constructor parameter.

**Comment by MarcusChr** [comment]
Hi.
A new branch called "removeReadData-constructor-branch" has been made with the untested code I have made so far.
Although I do have a question: should the value of this constructor parameter also affect the ToArray()-method?
I worry that implementing changes to the ToArray()-method could break existing projects.

**Comment by Orace** [comment]
I misread the code,  `BlockBasedMemoryStream` is already a `SlidingStream`

https://github.com/MarcusChr/BlockBasedMemoryStream/blob/3869fb164b16fc4aabd542339b1d794be72c81ba/BlockBasedMemoryStream.cs#L121-L124

`removeReadData` is set to `true`.
